# Generated by Django 2.1.7 on 2019-05-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_auto_20190506_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.CharField(default='글쓴이 없음', max_length=20),
        ),
    ]
